# Generated by Django 5.1.6 on 2025-02-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_roles_user_roles_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
    ]
