# Generated by Django 5.1.6 on 2025-02-17 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="roles_id",
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="users.roles"
            ),
            preserve_default=False,
        ),
    ]
