# Generated by Django 4.2.19 on 2025-02-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_roles_id_user_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="default/placeholder.png",
                null=True,
                upload_to="users/%Y/%m/%d",
                verbose_name="Фотография",
            ),
        ),
    ]
