# Generated by Django 4.2.19 on 2025-02-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0013_alter_user_email_alter_user_first_name_and_more"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("users", "0010_customuser_alter_roles_options_delete_user_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomUser",
            new_name="User",
        ),
    ]
