# Generated by Django 4.2.19 on 2025-02-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
