# Generated by Django 4.2.19 on 2025-02-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
