# Generated by Django 4.2.19 on 2025-02-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="survey",
            old_name="created_at",
            new_name="created_date",
        ),
        migrations.RenameField(
            model_name="survey",
            old_name="updated_at",
            new_name="updated_date",
        ),
    ]
