# Generated by Django 4.2.19 on 2025-02-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0002_rename_created_at_survey_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="selected_options",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="options",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
