# Generated by Django 4.2.19 on 2025-02-21 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0003_alter_user_roles_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="myapi.roles"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150),
        ),
    ]
