# Generated by Django 4.2.19 on 2025-03-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0003_answer_selected_options_question_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="selected_options",
        ),
        migrations.RemoveField(
            model_name="question",
            name="options",
        ),
        migrations.AlterField(
            model_name="answer",
            name="value",
            field=models.JSONField(blank=True, default=list, verbose_name="Ответ"),
        ),
        migrations.AlterField(
            model_name="question",
            name="value",
            field=models.JSONField(db_index=True, default=list, verbose_name="Вопрос"),
        ),
    ]
