# Generated by Django 4.2.19 on 2025-02-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0013_alter_user_email_alter_user_first_name_and_more"),
        ("myapi", "0005_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="users_user_set", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="users_user_permissions_set",
                to="auth.permission",
            ),
        ),
    ]
